= Frequently Asked Questions (FAQ)

If you don't see your question here, feel free to submit new ones to
link:mailto:&#100;o&#x63;&#115;&#x40;&#x64;&#111;&#99;k&#x65;&#x72;.&#99;&#x6f;&#x6d;[&#100;o&#x63;&#115;&#x40;&#x64;&#111;&#99;k&#x65;&#x72;.&#99;&#x6f;&#x6d;]. Or, you can fork https://github.com/docker/docker[the
repo] and contribute them yourself by editing
the documentation sources.

=== How much does Docker cost?

Docker is 100% free. It is open source, so you can use it without paying.

=== What open source license are you using?

We are using the Apache License Version 2.0, see it here:
[https://github.com/docker/docker/blob/master/LICENSE](
https://github.com/docker/docker/blob/master/LICENSE)

=== Does Docker run on Mac OS X or Windows?

Docker currently runs only on Linux, but you can use VirtualBox to run Docker in
a virtual machine on your box, and get the best of both worlds. Check out the
link:../installation/mac/#macosx[_Mac OS X_] and link:../installation/windows/#windows[_Microsoft
Windows_] installation guides. The small Linux
distribution boot2docker can be run inside virtual machines on these two
operating systems.

____

*Note:* if you are using a remote Docker daemon, such as Boot2Docker,
then _do not_ type the `sudo` before the `docker` commands shown in the
documentation's examples.

____

=== How do containers compare to virtual machines?

They are complementary. VMs are best used to allocate chunks of hardware
resources. Containers operate at the process level, which makes them very
lightweight and perfect as a unit of software delivery.

=== What does Docker add to just plain LXC?

Docker is not a replacement for LXC. "LXC" refers to capabilities of the Linux
kernel (specifically namespaces and control groups) which allow sandboxing
processes from one another, and controlling their resource allocations. On top
of this low-level foundation of kernel features, Docker offers a high-level tool
with several powerful functionalities:

* _Portable deployment across machines._ Docker defines a format for bundling
 an application and all its dependencies into a single object which can be
 transferred to any Docker-enabled machine, and executed there with the
 guarantee that the execution environment exposed to the application will be the
 same. LXC implements process sandboxing, which is an important pre-requisite
 for portable deployment, but that alone is not enough for portable deployment.
 If you sent me a copy of your application installed in a custom LXC
 configuration, it would almost certainly not run on my machine the way it does
 on yours, because it is tied to your machine's specific configuration:
 networking, storage, logging, distro, etc. Docker defines an abstraction for
 these machine-specific settings, so that the exact same Docker container can
 run - unchanged - on many different machines, with many different
 configurations.

* _Application-centric._ Docker is optimized for the deployment of
 applications, as opposed to machines. This is reflected in its API, user
 interface, design philosophy and documentation. By contrast, the `lxc` helper
 scripts focus on containers as lightweight machines - basically servers that
 boot faster and need less RAM. We think there's more to containers than just
 that.

* _Automatic build._ Docker includes link:../reference/builder/#dockerbuilder[_a tool for developers to automatically
 assemble a container from their source
 code_], with full control over application
 dependencies, build tools, packaging etc. They are free to use `make`, `maven`,
 `chef`, `puppet`, `salt,` Debian packages, RPMs, source tarballs, or any
 combination of the above, regardless of the configuration of the machines.

* _Versioning._ Docker includes git-like capabilities for tracking successive
 versions of a container, inspecting the diff between versions, committing new
 versions, rolling back etc. The history also includes how a container was
 assembled and by whom, so you get full traceability from the production server
 all the way back to the upstream developer. Docker also implements incremental
 uploads and downloads, similar to `git pull`, so new versions of a container
 can be transferred by only sending diffs.

* _Component re-use._ Any container can be used as a [_"base image"_](
 ../terms/image/#base-image-def) to create more specialized components. This can
 be done manually or as part of an automated build. For example you can prepare
 the ideal Python environment, and use it as a base for 10 different
 applications. Your ideal Postgresql setup can be re-used for all your future
 projects. And so on.

* _Sharing._ Docker has access to a https://hub.docker.com[public registry]
 where thousands of people have uploaded useful containers: anything from Redis,
 CouchDB, Postgres to IRC bouncers to Rails app servers to Hadoop to base images
 for various Linux distros. The
 link:../reference/api/registry_index_spec/#registryindexspec[_registry_] also
 includes an official "standard library" of useful containers maintained by the
 Docker team. The registry itself is open-source, so anyone can deploy their own
 registry to store and transfer private containers, for internal server
 deployments for example.

* _Tool ecosystem._ Docker defines an API for automating and customizing the
 creation and deployment of containers. There are a huge number of tools
 integrating with Docker to extend its capabilities. PaaS-like deployment
 (Dokku, Deis, Flynn), multi-node orchestration (Maestro, Salt, Mesos, Openstack
 Nova), management dashboards (docker-ui, Openstack Horizon, Shipyard),
 configuration management (Chef, Puppet), continuous integration (Jenkins,
 Strider, Travis), etc. Docker is rapidly establishing itself as the standard
 for container-based tooling.

=== What is different between a Docker container and a VM?

There's a great StackOverflow answer [showing the differences](
http://stackoverflow.com/questions/16047306/how-is-docker-io-different-from-a-normal-virtual-machine).

=== Do I lose my data when the container exits?

Not at all! Any data that your application writes to disk gets preserved in its
container until you explicitly delete the container. The file system for the
container persists even after the container halts.

=== How far do Docker containers scale?

Some of the largest server farms in the world today are based on containers.
Large web deployments like Google and Twitter, and platform providers such as
Heroku and dotCloud all run on container technology, at a scale of hundreds of
thousands or even millions of containers running in parallel.

=== How do I connect Docker containers?

Currently the recommended way to link containers is via the link primitive. You
can see details of how to link:/userguide/dockerlinks[work with links here].

Also useful for more flexible service portability is the link:/articles/ambassador_pattern_linking/[Ambassador linking
pattern].

=== How do I run more than one process in a Docker container?

Any capable process supervisor such as [http://supervisord.org/](
http://supervisord.org/), runit, s6, or daemontools can do the trick. Docker
will start up the process management daemon which will then fork to run
additional processes. As long as the processor manager daemon continues to run,
the container will continue to as well. You can see a more substantial example
link:/articles/using_supervisord/[that uses supervisord here].

=== What platforms does Docker run on?

Linux:

* Ubuntu 12.04, 13.04 et al
* Fedora 19/20+
* RHEL 6.5+
* CentOS 6+
* Gentoo
* ArchLinux
* openSUSE 12.3+
* CRUX 3.0+

Cloud:

* Amazon EC2
* Google Compute Engine
* Rackspace

=== How do I report a security issue with Docker?

You can learn about the project's security policy
https://www.docker.com/security/[here] and report security issues to this
link:mailto:security@docker.com[mailbox].

=== Why do I need to sign my commits to Docker with the DCO?

Please read [our blog post](
http://blog.docker.com/2014/01/docker-code-contributions-require-developer-certificate-of-origin/) on the introduction of the DCO.

=== When building an image, should I prefer system libraries or bundled ones?

*This is a summary of a discussion on the [docker-dev mailing list](
https://groups.google.com/forum/#!topic/docker-dev/L2RBSPDu1L0).*

Virtually all programs depend on third-party libraries. Most frequently, they
will use dynamic linking and some kind of package dependency, so that when
multiple programs need the same library, it is installed only once.

Some programs, however, will bundle their third-party libraries, because they
rely on very specific versions of those libraries. For instance, Node.js bundles
OpenSSL; MongoDB bundles V8 and Boost (among others).

When creating a Docker image, is it better to use the bundled libraries, or
should you build those programs so that they use the default system libraries
instead?

The key point about system libraries is not about saving disk or memory space.
It is about security. All major distributions handle security seriously, by
having dedicated security teams, following up closely with published
vulnerabilities, and disclosing advisories themselves. (Look at the https://www.debian.org/security/[Debian
Security Information] for an example of those
procedures.) Upstream developers, however, do not always implement similar
practices.

Before setting up a Docker image to compile a program from source, if you want
to use bundled libraries, you should check if the upstream authors provide a
convenient way to announce security vulnerabilities, and if they update their
bundled libraries in a timely manner. If they don't, you are exposing yourself
(and the users of your image) to security vulnerabilities.

Likewise, before using packages built by others, you should check if the
channels providing those packages implement similar security best practices.
Downloading and installing an "all-in-one" .deb or .rpm sounds great at first,
except if you have no way to figure out that it contains a copy of the OpenSSL
library vulnerable to the http://heartbleed.com/[Heartbleed] bug.

=== Why is `DEBIAN_FRONTEND=noninteractive` discouraged in Dockerfiles?

When building Docker images on Debian and Ubuntu you may have seen errors like:

----
unable to initialize frontend: Dialog
----

These errors don't stop the image from being built but inform you that the
installation process tried to open a dialog box, but was unable to. Generally,
these errors are safe to ignore.

Some people circumvent these errors by changing the `DEBIAN_FRONTEND`
environment variable inside the Dockerfile using:

----
ENV DEBIAN_FRONTEND=noninteractive
----

This prevents the installer from opening dialog boxes during installation which
stops the errors.

While this may sound like a good idea, it _may_ have side effects. The
`DEBIAN_FRONTEND` environment variable will be inherited by all images and
containers built from your image, effectively changing their behavior. People
using those images will run into problems when installing software
interactively, because installers will not show any dialog boxes.

Because of this, and because setting `DEBIAN_FRONTEND` to `noninteractive` is
mainly a 'cosmetic' change, we _discourage_ changing it.

If you _really_ need to change its setting, make sure to change it back to its
https://www.debian.org/releases/stable/i386/ch05s03.html.en[default value]
afterwards.

=== Why do I get `Connection reset by peer` when making a request to a service running in a container?

Typically, this message is returned if the service is already bound to your
localhost. As a result, requests coming to the container from outside are
dropped. To correct this problem, change the service's configuration on your
localhost so that the service accepts requests from all IPs. If you aren't sure
how to do this, check the documentation for your OS.

=== Where can I find more answers?

You can find more answers on:

* https://groups.google.com/d/forum/docker-user[Docker user mailinglist]
* https://groups.google.com/d/forum/docker-dev[Docker developer mailinglist]
* irc://chat.freenode.net#docker["IRC, docker on freenode"]
* https://github.com/docker/docker[GitHub]
* http://stackoverflow.com/search?q=docker[Ask questions on Stackoverflow]
* http://twitter.com/docker[Join the conversation on Twitter]

Looking for something else to read? Checkout the link:/userguide/[User Guide].