= Welcome to the Docker user guide

In the link:/[Introduction] you got a taste of what Docker is and how it
works. In this guide we're going to take you through the fundamentals of
using Docker and integrating it into your environment.

We’ll teach you how to use Docker to:

* Dockerize your applications.
* Run your own containers.
* Build Docker images.
* Share your Docker images with others.
* And a whole lot more!

We've broken this guide into major sections that take you through
the Docker life cycle:

== Getting started with Docker Hub

_How do I use Docker Hub?_

Docker Hub is the central hub for Docker. It hosts public Docker images
and provides services to help you build and manage your Docker
environment. To learn more:

Go to link:/userguide/dockerhub[Using Docker Hub].

== Dockerizing applications: A "Hello world"

_How do I run applications inside containers?_

Docker offers a _container-based_ virtualization platform to power your
applications. To learn how to Dockerize applications and run them:

Go to link:/userguide/dockerizing[Dockerizing Applications].

== Working with containers

_How do I manage my containers?_

Once you get a grip on running your applications in Docker containers
we're going to show you how to manage those containers. To find out
about how to inspect, monitor and manage containers:

Go to link:/userguide/usingdocker[Working With Containers].

== Working with Docker images

_How can I access, share and build my own images?_

Once you've learnt how to use Docker it's time to take the next step and
learn how to build your own application images with Docker.

Go to link:/userguide/dockerimages[Working with Docker Images].

== Linking containers together

Until now we've seen how to build individual applications inside Docker
containers. Now learn how to build whole application stacks with Docker
by linking together multiple Docker containers.

Go to link:/userguide/dockerlinks[Linking Containers Together].

== Managing data in containers

Now we know how to link Docker containers together the next step is
learning how to manage data, volumes and mounts inside our containers.

Go to link:/userguide/dockervolumes[Managing Data in Containers].

== Working with Docker Hub

Now we've learned a bit more about how to use Docker we're going to see
how to combine Docker with the services available on Docker Hub including
Trusted Builds and private repositories.

Go to link:/userguide/dockerrepos[Working with Docker Hub].

== Docker Compose

Docker Compose allows you to define a application's components – their containers,
configuration, links and volumes – in a single file. Then a single command
will set everything up and start your application running.

Go to link:/compose/[Docker Compose user guide].

== Docker Machine

Docker Machine helps you get Docker Engines up and running quickly. Machine
can set up hosts for Docker Engines on your computer, on cloud providers,
and/or in your data center, and then configure your Docker client to securely
talk to them.

Go to link:/machine/[Docker Machine user guide].

== Docker Swarm

Docker Swarm pools several Docker Engines together and exposes them as a single
virtual Docker Engine. It serves the standard Docker API, so any tool that already
works with Docker can now transparently scale up to multiple hosts.

Go to link:/swarm/[Docker Swarm user guide].

== Getting help

* http://www.docker.com/[Docker homepage]
* https://hub.docker.com[Docker Hub]
* http://blog.docker.com/[Docker blog]
* https://docs.docker.com/[Docker documentation]
* http://www.docker.com/gettingstarted/[Docker Getting Started Guide]
* https://github.com/docker/docker[Docker code on GitHub]
* https://groups.google.com/forum/#!forum/docker-user[Docker mailing
 list]
* Docker on IRC: irc.freenode.net and channel #docker
* http://twitter.com/docker[Docker on Twitter]
* Get http://stackoverflow.com/search?q=docker[Docker help] on
 StackOverflow
* http://www.docker.com/[Docker.com]